steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/jorge-test/servdocuments:${SHORT_SHA}', '-t',
          'us-central1-docker.pkg.dev/$PROJECT_ID/jorge-test/servdocuments','-f', 'Dockerfile' ]
  id: build
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/jorge-test/servdocuments:$SHORT_SHA']
  id: push
#Deploy container image to Cloud Deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'm2c-servdocuments-test-yorch',
    '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/jorge-test/servdocuments:$SHORT_SHA',
    '--region', 'us-central1',
    '--network', 'm2c-qa-network',
    '--subnet', 'm2c-qa-network-app',
    '--min-instances', '1',
    '--max-instances', '1',
    '--cpu', '1',
    '--memory', '256Mi',
    '--port', '8080',
    '--allow-unauthenticated']
  id: deploy
images:
- us-central1-docker.pkg.dev/$PROJECT_ID/jorge-test/servdocuments