apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-python-pipeline-test
    app.kubernetes.io/managed-by: google-cloud-deploy
    deploy.cloud.google.com/delivery-pipeline-id: hello-world-python-pipeline
    deploy.cloud.google.com/location: us-central1
    deploy.cloud.google.com/project-id: came-devops-dev
    deploy.cloud.google.com/release-id: manual-v1
    deploy.cloud.google.com/target-id: test
  name: hello-world-python-pipeline-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-python-pipeline-test
  template:
    metadata:
      labels:
        app: hello-world-python-pipeline-test
        app.kubernetes.io/managed-by: google-cloud-deploy
        deploy.cloud.google.com/delivery-pipeline-id: hello-world-python-pipeline
        deploy.cloud.google.com/location: us-central1
        deploy.cloud.google.com/project-id: came-devops-dev
        deploy.cloud.google.com/release-id: manual-v1
        deploy.cloud.google.com/target-id: test
    spec:
      containers:
        - image: hello-world-python
          name: hello-world-python-pipeline-test
